sudo: false

language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  - DB=MYSQL CORE_RELEASE=3.2

matrix:
  include:
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3.1
    - php: 5.6
      env: DB=PGSQL CORE_RELEASE=3.2
  allow_failures:
    - php: 7.0

before_script:
  - composer self-update || true
  - composer install

script:
  - /vendor/bin/phpunit tests/
